### ISSUE TITLE
Question about Decoding method

### ISSUE THREAD

**Issue by Teddy12155555** [Qinyu-Allen-Zhao/LVLM-LP#2]
Hi, Qinyu-Allen-Zhao,
I hope this message finds you well. Thank you for your excellent work—it has been very inspiring to me. However, as a beginner, there are some parts I don't fully understand, and I was hoping you could assist me. 

In section 4.6 of your paper, "Decoding method guided by linear probing," you mention using a new decoding method, where a linear classifier is followed by task-specific templates to guide VLM in continuing the response. Could you please guide me on where I can find the implementation of this part in the code?

**Comment by Qinyu-Allen-Zhao** [comment]
Thank you for your interest! Sorry for my late response! We modifed the codes in the Transformers Python package. We didn't upload that, considering the package is very large and maintained by others. 

But the changes are small, like several lines. I will try to write a guidance in the README file (tomorrow! I must set a deadline for me!)

Qinyu

**Comment by Qinyu-Allen-Zhao** [comment]
Hi! I have modified the README file and added a step-by-step guide to modify your transformers package. Let me know if you have any questions!

https://github.com/Qinyu-Allen-Zhao/LVLM-LP/blob/cb3081e491e8613120434d5c70fdc13db97355cf/README.md?plain=1#L76-L165

Qinyu

**Comment by Teddy12155555** [comment]
Thank you for your reply and explanation. I completely understand now, and I really appreciate your help.
